services:
  - type: web
    name: ke-group-scadenziario
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: LOGIN_USERNAME
        sync: false
      - key: LOGIN_PASSWORD
        sync: false
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "1"
